package pl.edu.wat.wcy.rrfgpplugin;

public class RRfGPPanel extends javax.swing.JPanel {

    /**
     * Creates new form RfGPPanel
     */
    public RRfGPPanel() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nodeLabel = new javax.swing.JLabel();
        degreeLabel = new javax.swing.JLabel();
        nodeField = new javax.swing.JTextField();
        degreeField = new javax.swing.JTextField();
        numberOfStepsLabel = new javax.swing.JLabel();
        numberOfStepsField = new javax.swing.JTextField();

        nodeLabel.setText(org.openide.util.NbBundle.getMessage(RRfGPPanel.class, "RRfGPPanel.nodeLabel.text")); // NOI18N

        degreeLabel.setText(org.openide.util.NbBundle.getMessage(RRfGPPanel.class, "RRfGPPanel.degreeLabel.text")); // NOI18N

        nodeField.setText(org.openide.util.NbBundle.getMessage(RRfGPPanel.class, "RRfGPPanel.nodeField.text")); // NOI18N

        degreeField.setText(org.openide.util.NbBundle.getMessage(RRfGPPanel.class, "RRfGPPanel.degreeField.text")); // NOI18N

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("pl/edu/wat/wcy/rrfgpplugin/Bundle"); // NOI18N
        numberOfStepsLabel.setText(bundle.getString("RRfGPPanel.numberOfStepsLabel.text")); // NOI18N

        numberOfStepsField.setText(bundle.getString("RRfGPPanel.numberOfStepsField.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(nodeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(numberOfStepsLabel)
                            .addComponent(degreeLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(degreeField, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                            .addComponent(numberOfStepsField))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nodeLabel)
                    .addComponent(nodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(degreeLabel)
                    .addComponent(degreeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numberOfStepsLabel)
                    .addComponent(numberOfStepsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JTextField degreeField;
    private javax.swing.JLabel degreeLabel;
    protected javax.swing.JTextField nodeField;
    private javax.swing.JLabel nodeLabel;
    protected javax.swing.JTextField numberOfStepsField;
    private javax.swing.JLabel numberOfStepsLabel;
    // End of variables declaration//GEN-END:variables
}
